forntend/FEPetServices/FEPetServices/Areas/Manager/Controllers/OrdersRoomController.cs
using FEPetServices.Form.OrdersForm;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Net.Http.Headers;
using System.Text.Json;


namespace FEPetServices.Areas.Manager.Controllers
{
    [ResponseCache(Location = ResponseCacheLocation.None, NoStore = true)]
    [Authorize(Policy = "ManaOnly")]
    public class OrdersRoomController : Controller
    {
        private readonly HttpClient _client = null;
        private string DefaultApiUrl = "";
        private readonly IConfiguration configuration;

        public OrdersRoomController(IConfiguration configuration)
        {
            this.configuration = configuration;
            _client = new HttpClient();
            var contentType = new MediaTypeWithQualityHeaderValue("application/json");
            _client.DefaultRequestHeaders.Accept.Add(contentType);
            DefaultApiUrl = configuration.GetValue<string>("DefaultApiUrl");
            //DefaultApiUrl = "https://localhost:7255/api/";

        }

        [HttpGet]
        public async Task<IActionResult> Index()
        {
            ViewBag.Title = "Danh sách đơn phòng đã đặt";
            //https://localhost:7255/api/Order/getOrderRoom
            //HttpResponseMessage response = await _client.GetAsync("https://localhost:7255/api/" + "Order/getOrderRoom");
            HttpResponseMessage response = await _client.GetAsync(DefaultApiUrl + "Order/getOrderRoom");
            if (response.IsSuccessStatusCode)
            {
                string responseContent = await response.Content.ReadAsStringAsync();

                var options = new JsonSerializerOptions
                {
                    PropertyNameCaseInsensitive = true
                };

                List<OrderForm> orderLists = System.Text.Json.JsonSerializer.Deserialize<List<OrderForm>>(responseContent, options);
                return View(orderLists);
            }
            else
            {
                TempData["ErrorLoadingDataToast"] = "Lỗi hệ thống vui lòng thử lại sau";
                return View();
            }
        }

        [HttpGet]
        public async Task<IActionResult> OrderRoomDetail(int id)
        {
            ViewBag.Title = "Chi tiết phòng đã đặt";
            //HttpResponseMessage response = await _client.GetAsync("https://localhost:7255/api/" + "Order/" + id);
            HttpResponseMessage response = await _client.GetAsync(DefaultApiUrl + "Order/" + id);
            if (response.IsSuccessStatusCode)
            {
                string responseContent = await response.Content.ReadAsStringAsync();

                var options = new JsonSerializerOptions
                {
                    PropertyNameCaseInsensitive = true
                };
                OrderForm orderDetail = System.Text.Json.JsonSerializer.Deserialize<OrderForm>(responseContent, options);
                return View(orderDetail);
            }
            else
            {
                TempData["ErrorLoadingDataToast"] = "Lỗi hệ thống vui lòng thử lại sau";
                return View();
            }
        }

        [HttpPost]
        public async Task<IActionResult> OrderRoomDetail(int id, [FromForm] Status status)
        {
            status.newStatusProduct = "";
            status.newStatusService = "";

            //HttpResponseMessage response = await _client.PutAsJsonAsync("https://localhost:7255/api/" + "Order/changeStatus?Id=" + id, status);
            HttpResponseMessage response = await _client.PutAsJsonAsync(DefaultApiUrl + "Order/changeStatus?Id=" + id, status);
            if (response.IsSuccessStatusCode)
            {
                TempData["SuccessToast"] = "Cập nhật thành công";
                return RedirectToAction("OrderRoomDetail", new { id = id });
            }
            else
            {
                TempData["ErrorLoadingDataToast"] = "Lỗi hệ thống vui lòng thử lại sau";
                return View();
            }
        }
    }
}

forntend/FEPetServices/FEPetServices/Areas/Manager/Views/OrdersRoom/Index.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    @*<link href="//cdn.datatables.net/buttons/1.7.1/css/buttons.dataTables.min.css" rel="stylesheet">*@
    <link href="//cdn.datatables.net/1.13.4/css/jquery.dataTables.min.css" rel="stylesheet">
    <link href="~/css/toastNotification.css" rel="stylesheet" />
    <link href="~/css/datatable.css" rel="stylesheet" />
    <link href="~/css/orders/stylesheet.css" rel="stylesheet" />
</head>
<body>
    <div>
        <h1>Danh sách phòng được đặt</h1>
    </div>
    <div>
        <table id="lists">
            <thead>
                <tr>
                    <th>No.</th>
                    <th>Tên</th>
                    <th>Số điện thoại</th>
                    <th>Ngày đặt đơn</th>
                    <th>Trạng thái đơn hàng</th>
                    <th>Chi tiết</th>
                </tr>
            </thead>
            <tbody>
                @if (Model != null && Model.Count > 0)
                {
                    int itemCount = 0;
                    foreach (var orderLists in Model)
                    {
                        itemCount++;
                        <tr>
                            <td>@itemCount</td>
                            <td>@orderLists?.FullName</td>
                            <td>@orderLists?.Phone</td>
                            <td>@orderLists?.OrderDate</td>
                            <td>
                                @if (orderLists?.OrderStatus.Trim() == "Confirmed")
                                {
                                    <span style="display:inline-block;background-color: #43e240;" class="badge badge-info">Đã trả phòng</span>
                                }
                                else if (orderLists?.OrderStatus.Trim() == "Refund")
                                {
                                    <span style="display:inline-block;background-color: #43e240;" class="badge badge-info">Hoàn tiên</span>
                                }
                                else if (orderLists?.OrderStatus.Trim() == "Placed")
                                {
                                    <span style="display:inline-block;background-color: #43e240;" class="badge badge-info">Chờ nhận phòng</span>
                                }
                                else if (orderLists?.OrderStatus.Trim() == "Cancelled")
                                {
                                    <span style="display:inline-block;background-color: #43e240;" class="badge badge-info">Phòng bị huỷ</span>
                                }
                                else if (orderLists?.OrderStatus.Trim() == "Processing")
                                {
                                    <span style="display:inline-block;background-color: #43e240;" class="badge badge-info">Đã nhận phòng</span>
                                }
                            </td>
                            <td>
                                <a class="btn-detail" href="~/Manager/OrdersRoom/OrderRoomDetail?id=@orderLists.OrderId">Chi tiết</a>
                            </td>
                        </tr>
                    }
                }
            </tbody>
            <tfoot>
                @if (!string.IsNullOrEmpty(TempData["ErrorLoadingDataToast"] as string))
                {
                    <div style="margin: 0 30px;" class="alert alert-danger">
                        <span style="color:red">@TempData["ErrorLoadingDataToast"]</span>
                    </div>
                }
            </tfoot>
        </table>
    </div>
</body>
<script>
    $(document).ready(function () {
        // Khởi tạo DataTables
        var table = $('#lists').DataTable({
            "responsive": true,
            "paging": true,
            "lengthMenu": [[10, 25, 50, -1], [10, 25, 50, "All"]],
            "searching": true,
            "ordering": true,
            "info": true,
            "autoWidth": false,
            "dom": 'Bfrtip',
            "buttons": [
                {
                    extend: 'copy',
                    text: 'Sao chép',
                },
                {
                    extend: 'csv',
                    text: 'Xuất CSV',
                    filename: 'Danh sách order'
                },
                {
                    extend: 'excel',
                    text: 'Xuất Excel',
                    filename: 'Danh sách order'
                },
                {
                    extend: 'pdf',
                    text: 'Xuất PDF',
                    filename: 'Danh sách order'
                },
                {
                    extend: 'print',
                    text: 'In',
                }
            ],

            "columnDefs": [
                { "targets": [0], "width": "5%" },
                { "targets": [1], "width": "20%" },
                { "targets": [2], "width": "15%" },
                { "targets": [3], "width": "20%" },
                { "targets": [4], "width": "25%" },
                { "targets": [5], "width": "15%" },
            ],
            "language": {
                "lengthMenu": "Hiển thị _MENU_ dòng",
                "info": "Hiển thị _START_ - _END_ trên tổng cộng _TOTAL_ dòng",
                "search": "Tìm kiếm:",
                "paginate": {
                    "first": "Đầu",
                    "last": "Cuối",
                    "next": "Tiếp",
                    "previous": "Trước"
                }
            },
        });
    });
</script>
</html>

forntend/FEPetServices/FEPetServices/Areas/Manager/Views/OrdersRoom/OrderRoomDetail.cshtml
<!DOCTYPE html>
<html>
<head>
    <title>Order Detail</title>
    <link href="~/css/manager/print.css" rel="stylesheet" />
    <link href="~/css/toastNotification.css" rel="stylesheet" />
    <link href="~/css/orders/stylesheet.css" rel="stylesheet" />
    <link href="~/css/manager/table.css" rel="stylesheet" />
</head>
<body>
    <div class="container print-container">
        <h2>Chi tiết đơn hàng</h2>
        @*Thông tin đơn hàng*@
        <div class="form-group row">
            <label class="col-sm-3 col-form-label">Mã đơn hàng :</label>
            <div class="col-sm-9">
                <input type="text" readonly class="form-control-plaintext" value="@Model.OrderId">
            </div>
        </div>
        <div class="form-group row">
            <label class="col-sm-3 col-form-label">Ngày mua hàng :</label>
            <div class="col-sm-9">
                <input type="text" readonly class="form-control-plaintext" value="@Model?.OrderDate">
            </div>
        </div>
        <div class="form-group row">
            <label class="col-sm-3 col-form-label">Trạng thái :</label>
            <div class="col-sm-9" style="padding-top:8px">
                @if (Model?.OrderStatus.Trim() == "Confirmed")
                {
                    <span style="display:inline-block" class="badge badge-info">Đã trả phòng</span>
                }
                else if (Model?.OrderStatus.Trim() == "Processing")
                {
                    <span style="display:inline-block" class="badge badge-info">Đã nhận phòng</span>
                }
                else if (Model?.OrderStatus.Trim() == "Refund")
                {
                    <span style="display:inline-block" class="badge badge-info">Hoàn tiền</span>
                }
                else if (Model?.OrderStatus.Trim() == "Placed")
                {
                    <span style="display:inline-block" class="badge badge-info">Chờ nhận phòng</span>
                }
                else if (Model?.OrderStatus.Trim() == "Cancelled")
                {
                    <span style="display:inline-block" class="badge badge-info">Phòng bị huỷ </span>
                }
            </div>
        </div>
        @*Thông tin khách hàng*@
        <h3>Thông tin khách hàng</h3>
        <div class="form-group row">
            <label class="col-sm-3 col-form-label">Tên Khách Hàng :</label>
            <div class="col-sm-9">
                <input type="text" readonly class="form-control-plaintext" value="@Model.FullName">
            </div>
        </div>
        <div class="form-group row">
            <label class="col-sm-3 col-form-label">Địa chỉ :</label>
            <div class="col-sm-9">
                <input type="text" readonly class="form-control-plaintext"
                       value="@Model.Province , @Model.District , @Model.Commune">
            </div>
        </div>
        <div class="form-group row">
            <label class="col-sm-3 col-form-label">Địa chỉ cụ thể :</label>
            <div class="col-sm-9">
                <input type="text" readonly class="form-control-plaintext" value="@Model.Address">
            </div>
        </div>
        <div class="form-group row">
            <label class="col-sm-3 col-form-label">Thông tin liên hệ :</label>
            <div class="col-sm-9">
                <input type="text" readonly class="form-control-plaintext" value="@Model.Phone">
            </div>
        </div>

        @if (Model.BookingRoomDetails != null && Model.BookingRoomDetails.Count > 0)
        {
            <h4>Thông tin phòng</h4>
            <div style="overflow-x:auto;">
                <table class="table">
                    <thead>
                        <tr>
                            <th>Tên Phòng</th>
                            <th>Giá phòng</th>
                            <th>Dịch vụ trong phòng</th>
                            <th>Thời gian</th>
                            <th>Tổng giá</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var roomDetail in Model.BookingRoomDetails)
                        {
                            <tr>
                                <td>@roomDetail.Room.RoomName</td>
                                <td>
                                    @($"{roomDetail.Price:n0}".Replace(",", ".")) VNĐ
                                </td>
                                <td>
                                    @foreach (var roomService in Model.BookingRoomServices)
                                    {
                                        <div style="width: 250px;" class="room-info-detail-service">
                                            <p style="font-size:.8rem;">Dịch vụ: @roomService.Service.ServiceName</p>
                                        </div>
                                    }
                                </td>
                                <td>
                                    <div class="content-detail-time-service">
                                        <p style="font-size:.8rem;">Thời gian bắt đầu: <br></br> @roomDetail?.StartDate</p>
                                        <p style="font-size:.8rem;">Thời gian kêt thúc: <br></br> @roomDetail?.EndDate </p>
                                    </div>
                                </td>
                                <td>
                                    @($"{roomDetail.TotalPrice:n0}".Replace(",", ".")) VNĐ
                                </td>
                            </tr>
                        }
                    </tbody>
                </table>
            </div>
        }

        <div style="margin-bottom:0" class="form-group row">
            <p class="col-sm-6 col-form-label">Hoá đơn</p>
            <p class="col-sm-6 col-form-label" style="text-align:end">Thanh toán</p>
        </div>
        <div class="form-group row">
            <p class="col-sm-6 col-form-label"><strong>#</strong></td>
            <p class="col-sm-6 col-form-label" style="text-align:end"><strong>@($"{Model.TotalPrice:n0}".Replace(",", ".")) VNĐ</strong></p>
        </div>

        <div class="work-container-inner">
            @if (Model != null && Model.TypePay != null && Model.TypePay.Trim() == "cash")
            {
                <p>Thanh toán trực tiếp</p>
            }
            @if (Model != null && Model.TypePay != null && @Model.TypePay.Trim() == "vnpay")
            {
                <p>Thanh toán bằng hình thức chuyển khoản</p>
            }
            @if (!@Model.StatusPayment)
            {
                <span class="badge badge-info">Chưa thanh toán</span>
            }
            else
            {
                <span class="badge badge-info">Đã thanh toán</span>
            }
        </div>
        <form method="post" asp-controller="OrdersRoom" asp-action="OrderRoomDetail">
            @if (Model.OrderStatus.Trim() == "Placed")
            {
                <input type="hidden" name="Id" value="@Model?.OrderId" />
                <input type="hidden" name="oldStatus" value="@Model?.OrderStatus.Trim()" />

                <select style="margin-bottom:12px;" class="form-select select-status" name="newStatus">
                    <option value="Processing">Xác nhận khách nhận phòng</option>
                    <option value="Cancelled">Xác nhận huỷ phòng</option>
                </select>

                <button class="btn btn-primary" type="submit">Xác nhận</button>
            }
            @if (Model.OrderStatus.Trim() == "Processing")
            {
                <input type="hidden" name="Id" value="@Model?.OrderId" />
                <input type="hidden" name="oldStatus" value="@Model?.OrderStatus.Trim()" />

                <select style="margin-bottom:12px;" class="form-select select-status" name="newStatus">
                    <option value="Confirmed">Xác nhận trả phòng</option>
                    @if (Model?.OrderStatus.Trim() != "Processing")
                    {
                        <option value="Cancelled">Xác nhận huỷ phòng</option>
                    }
                </select>

                <button class="btn btn-primary" type="submit">Xác nhận</button>
            }
        </form>

        <button class="btn btn-primary" onclick="window.print()">In hoá đơn</button>
        <div class="btn-group">
            <a class="btn btn-primary" href="~/Manager/OrdersRoom/Index">Trở lại</a>
        </div>
    </div>
</body>
</html>