forntend/FEPetServices/FEPetServices/Areas/Manager/Controllers/ChangePasswordController.cs
using FEPetServices.Form;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Net.Http.Headers;
using System.Security.Claims;

namespace FEPetServices.Areas.Manager.Controllers
{
    [ResponseCache(Location = ResponseCacheLocation.None, NoStore = true)]
    [Authorize(Policy = "ManaOnly")]
    public class ChangePasswordController : Controller
    {
        private readonly HttpClient _client = null;
        private string DefaultApiUrl = "";
        private readonly IConfiguration configuration;

        public ChangePasswordController(IConfiguration configuration)
        {
            this.configuration = configuration;
            _client = new HttpClient();
            var contentType = new MediaTypeWithQualityHeaderValue("application/json");
            _client.DefaultRequestHeaders.Accept.Add(contentType);
            DefaultApiUrl = configuration.GetValue<string>("DefaultApiUrl");
            //DefaultApiUrl = "https://pet-service-api.azurewebsites.net/api/Account";
        }
        public async Task<IActionResult> Index([FromForm] ChangePassword changePassword)
        {
            ViewBag.Title = "Đổi mật khẩu";
            ClaimsPrincipal claimsPrincipal = HttpContext.User as ClaimsPrincipal;
            string email = claimsPrincipal.FindFirstValue(ClaimTypes.Email);

            if (changePassword.OldPassword == null || changePassword.NewPassword == null)
            {
                return View();
            }

            if (changePassword.NewPassword != changePassword.ConfirmNewPassword)
            {
                ViewBag.ErrorToast = "Mật khẩu mới và xác nhận lại mật khẩu không trùng khớp";
                return View();
            }
            else if (changePassword.NewPassword.Length < 8)
            {
                ViewBag.ErrorToast = "Mật khẩu mới phải có ít nhất 8 ký tự";
                return View();
            }

            string apiUrl = $"https://pet-service-api.azurewebsites.net/api/Account/newpassword?email={email}&oldpassword={changePassword.OldPassword}&newpassword={changePassword.NewPassword}&confirmnewpassword={changePassword.ConfirmNewPassword}";

            HttpResponseMessage response = await _client.PutAsync(apiUrl, null);

            if (response.IsSuccessStatusCode)
            {
                ViewBag.SuccessToast = "Đổi mật khẩu thành công";
                return View();
            }
            else
            {
                ViewBag.ErrorToast = "Mật khẩu cũ không chính xác";
                return View();
            }
        }

    }
}

forntend/FEPetServices/FEPetServices/Areas/Manager/Views/ChangePassword/Index.cshtml
@model FEPetServices.Form.ChangePassword

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Đổi mật khẩu</title>
    <link href="~/css/toastNotification.css" rel="stylesheet" />
</head>
<body>
    <div class="container-xl mt-4">
        <hr class="mt-0 mb-4">
        <div class="row">
            <div class="col-xl-12">
                <div class="card mb-4">
                    <div class="card-header">Đổi mật khẩu</div>
                    <div class="card-body">
                        <form method="post" asp-controller="ChangePassword" asp-action="Index" enctype="multipart/form-data">
                            <div class="mb-3">
                                <label for="OldPassword" class="form-label">Mật khẩu cũ</label>
                                <input asp-area="Manager" asp-for="OldPassword" class="form-control" id="OldPassword" name="OldPassword" type="password" placeholder="Nhập mật khẩu cũ" required>
                            </div>

                            <div class="mb-3">
                                <label for="NewPassword" class="form-label">Mật khẩu mới</label>
                                <div class="input-group">
                                    <input asp-area="Manager" asp-for="NewPassword" class="form-control" id="NewPassword" name="NewPassword" type="password" placeholder="Nhập mật khẩu mới" required>
                                    <span class="input-group-text" id="showPassword">
                                        <i class="far fa-eye" id="eyeIcon"></i>
                                    </span>
                                </div>
                            </div>

                            <div class="mb-3">
                                <label for="ConfirmNewPassword" class="form-label">Nhập lại mật khẩu mới</label>
                                <div class="input-group">
                                    <input class="form-control" id="ConfirmNewPassword" name="ConfirmNewPassword" type="password" placeholder="Nhập lại mật khẩu mới" required>
                                    <span class="input-group-text" id="showConfirmPassword">
                                        <i class="far fa-eye" id="eyeConfirmIcon"></i>
                                    </span>
                                </div>
                                <div id="passwordMismatchMessage" style="color: red;"></div> 
                            </div>
                            <button class="btn btn-primary" type="submit">Đổi mật khẩu</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</body>
    <script src="~/js/checkpassword.js"></script>
</html>